In [2]:
import pickle
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

pd.options.display.max_columns = None

In [3]:
dfs = []

In [9]:
dim = 10
#file = open('comp_himmelbau_withmars_sigma=0.1.pickle', 'rb')
#file = open('comp_randompoly_dim=5_maxorder=5_sigma=0.4.pickle', 'rb')
file = open('comp_randompoly_dim=10_maxorder=5_sigma=0.0.pickle', 'rb')
data = pickle.load(file)

dat = sum(data)/len(data)
for n in dat.n.unique():
    d = dat.loc[dat.n == n, :].mean()
    d['dim']=dim
    dfs.append(d)

In [4]:
# for dat in data:
#     # find values that are way to large, indicating some unusual problem with the method
#     threshold = 10
#     # dat.loc[dat['BMLR_cut0'] > threshold, 'BMLR_cut0'] = np.nan
#     # dat.loc[dat['BMLR_cut10'] > threshold, 'BMLR_cut10'] = np.nan
#     # dat.loc[dat['BMLR_cut20'] > threshold, 'BMLR_cut20'] = np.nan
#     # dat.loc[dat['BMLR_cut30'] > threshold, 'BMLR_cut30'] = np.nan
#     # replace them with average value
#     dat.fillna(dat.mean(), inplace=True)

In [6]:
# dat = sum(data)/len(data)
# for n in dat.n.unique():
#     d = dat.loc[dat.n == n, :].mean()
#     d['dim']=dim
#     dfs.append(d)

In [10]:
df = pd.DataFrame(dfs)
df

,n,sigma,rmse_RF,rmse_CB,rmse_SVR,rmse_MARS,mape_RF,mape_CB,mape_SVR,mape_MARS,rmse_BMLR_cut0,rmse_BMLR_cut10,rmse_BMLR_cut20,rmse_BMLR_cut30,rmse_BMLR_cut0_y,rmse_BMLR_cut10_y,rmse_BMLR_cut20_y,rmse_BMLR_cut30_y,mape_BMLR_cut0,mape_BMLR_cut10,mape_BMLR_cut20,mape_BMLR_cut30,mape_BMLR_cut0_y,mape_BMLR_cut10_y,mape_BMLR_cut20_y,mape_BMLR_cut30_y,dim
0,1000.0,0.0,0.034267,0.013771,0.012992,0.007271,4.488427e+11,3.713743e+11,2.131235e+11,4.370895e+10,0.000000,0.000000,0.0,0.0,0.070252,0.070292,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,4.742119e+11,4.742119e+11,0.0,0.0,5.0
1,1000.0,0.1,0.110141,0.109461,0.110154,0.102985,4.914384e-01,4.619840e-01,4.887885e-01,4.378726e-01,0.000000,0.000000,0.0,0.0,0.158385,0.158346,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,6.262941e-01,6.262354e-01,0.0,0.0,5.0
2,1000.0,0.2,0.213542,0.217723,0.210665,0.207090,1.731422e+00,1.723519e+00,1.735706e+00,1.595131e+00,0.000000,0.000000,0.0,0.0,0.292512,0.292513,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,2.055085e+00,2.055160e+00,0.0,0.0,5.0
3,1000.0,0.3,0.000000,0.325394,0.000000,0.311195,0.000000e+00,3.522625e+00,0.000000e+00,3.686021e+00,0.434935,0.435094,0.0,0.0,0.432096,0.432040,0.0,0.0,4.264521e+00,4.270282e+00,0.0,0.0,4.252185e+00,4.252704e+00,0.0,0.0,5.0
4,1000.0,0.4,0.000000,0.433884,0.000000,0.407817,0.000000e+00,3.395429e+00,0.000000e+00,3.337706e+00,0.576736,0.577897,0.0,0.0,0.572231,0.572235,0.0,0.0,4.205138e+00,4.210465e+00,0.0,0.0,4.207183e+00,4.207156e+00,0.0,0.0,5.0
5,2500.0,0.0,0.000000,0.012455,0.000000,0.010036,0.000000e+00,1.222944e+11,0.000000e+00,1.761392e+10,0.095316,0.095316,0.0,0.0,0.095316,0.095316,0.0,0.0,3.093339e+11,3.093339e+11,0.0,0.0,3.093339e+11,3.093339e+11,0.0,0.0,10.0

In [16]:
for col_name in df.columns:
    if 'mape' in col_name or 'cut20' in col_name or 'cut30' in col_name:
        df.drop([col_name], axis=1, inplace=True)

In [17]:
df

,n,sigma,rmse_RF,rmse_CB,rmse_SVR,rmse_MARS,rmse_BMLR_cut0,rmse_BMLR_cut10,rmse_BMLR_cut0_y,rmse_BMLR_cut10_y,dim
0,1000.0,0.0,0.034267,0.013771,0.012992,0.007271,0.000000,0.000000,0.070252,0.070292,5.0
1,1000.0,0.1,0.110141,0.109461,0.110154,0.102985,0.000000,0.000000,0.158385,0.158346,5.0
2,1000.0,0.2,0.213542,0.217723,0.210665,0.207090,0.000000,0.000000,0.292512,0.292513,5.0
3,1000.0,0.3,0.000000,0.325394,0.000000,0.311195,0.434935,0.435094,0.432096,0.432040,5.0
4,1000.0,0.4,0.000000,0.433884,0.000000,0.407817,0.576736,0.577897,0.572231,0.572235,5.0
5,2500.0,0.0,0.000000,0.012455,0.000000,0.010036,0.095316,0.095316,0.095316,0.095316,10.0

In [19]:
0.07/0.013

5.384615384615385

In [25]:
0.57/0.4

1.4249999999999998

In [23]:
0.3/0.21

1.4285714285714286

In [24]:
0.158/0.11

1.4363636363636363