In [2]:
import pickle
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

pd.options.display.max_columns = None

In [3]:
dfs = []

In [16]:
#file = open('comp_himmelbau_withmars_sigma=0.1.pickle', 'rb')
file = open('comp_randompoly_dim=5_maxorder=5_sigma=0.2.pickle', 'rb')
data = pickle.load(file)

In [5]:
for dat in data:
    # find values that are way to large, indicating some unusual problem with the method
    threshold = 10
    # dat.loc[dat['BMLR_cut0'] > threshold, 'BMLR_cut0'] = np.nan
    # dat.loc[dat['BMLR_cut10'] > threshold, 'BMLR_cut10'] = np.nan
    # dat.loc[dat['BMLR_cut20'] > threshold, 'BMLR_cut20'] = np.nan
    # dat.loc[dat['BMLR_cut30'] > threshold, 'BMLR_cut30'] = np.nan
    # replace them with average value
    dat.fillna(dat.mean(), inplace=True)

In [17]:
dat = sum(data)/len(data)
for n in dat.n.unique():
    d = dat.loc[dat.n == n, :].mean()
    dfs.append(d)

In [18]:
df = pd.DataFrame(dfs)
df
#df.to_csv('himmelbau.csv')

,n,sigma,rmse_RF,rmse_CB,rmse_SVR,rmse_MARS,mape_RF,mape_CB,mape_SVR,mape_MARS,rmse_BMLR_cut0,rmse_BMLR_cut10,rmse_BMLR_cut20,rmse_BMLR_cut30,rmse_BMLR_cut0_y,rmse_BMLR_cut10_y,rmse_BMLR_cut20_y,rmse_BMLR_cut30_y,mape_BMLR_cut0,mape_BMLR_cut10,mape_BMLR_cut20,mape_BMLR_cut30,mape_BMLR_cut0_y,mape_BMLR_cut10_y,mape_BMLR_cut20_y,mape_BMLR_cut30_y
0,1000.0,0.0,0.034267,0.013771,0.012992,0.007271,4.488427e+11,3.713743e+11,2.131235e+11,4.370895e+10,0.0,0.0,0.0,0.0,0.070252,0.070292,0.0,0.0,0.0,0.0,0.0,0.0,4.742119e+11,4.742119e+11,0.0,0.0
1,1000.0,0.1,0.110141,0.109461,0.110154,0.102985,4.914384e-01,4.619840e-01,4.887885e-01,4.378726e-01,0.0,0.0,0.0,0.0,0.158385,0.158346,0.0,0.0,0.0,0.0,0.0,0.0,6.262941e-01,6.262354e-01,0.0,0.0
2,1000.0,0.2,0.213542,0.217723,0.210665,0.207090,1.731422e+00,1.723519e+00,1.735706e+00,1.595131e+00,0.0,0.0,0.0,0.0,0.292512,0.292513,0.0,0.0,0.0,0.0,0.0,0.0,2.055085e+00,2.055160e+00,0.0,0.0

In [15]:
0.158/0.1

1.5799999999999998